### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by Iameaszy**

### CODE REVIEW

**Comment by Yusadolat** [comment]
I have tested the both Sign-in and Signup. They both works well.  Jazakallahu khairan.
I'm just concern about the ES6 class used in the implementation on Auth while other are Functional JS. The rest of the team might find it difficult to relate with and it also introduces two different patterns to the codebase. What do you think?

**Comment by Iameaszy** [comment]
Well, we can use both. Just that the project must have a structure we will share with people that will contribute. Which one do you think we should go with? I like using classes in the modules

**Comment by Yusadolat** [comment]
I believe the rest of the team would prefer the Functional paradigm because that's what most tutorials and courses are used these days So let's stick with that. We can Create a poll to get others' opinions.

**Comment by Yusadolat** [comment]
@all-contributors

Adds @Iameaszy  as a contributor for test, code.

**Comment by Yusadolat** [comment]
@all-contributors please add @Iameaszy for code, doc and infra

**Pull request merged**
