### PR TITLE
Feature/restructured files

### PR DESCRIPTION
**Pull request by kennie-larkson**
Done

### CODE REVIEW

**Comment by Yusadolat** [comment]
The Events and Halaqaat Folders do not include `Routes`. You can delete the Model, Controllers and Routes folder once the file has been moved.

**Comment by Yusadolat** [comment]
#19

**Comment by kennie-larkson** [comment]
So i deleted a folder from local and pushed up in here but it is now complaining of a conflict because of that and suggested I resolve the conflict. What is there to resolve? 
Please, help check it out

**Comment by Yusadolat** [comment]
The button to resolve is not even active LOL

**Comment by Yusadolat** [comment]
Send a new PR Please!

**Pull request closed without merging**
